### ISSUE TITLE
Limit blob storage usage

### ISSUE THREAD

**Issue by omersalam** [Azure-Samples/video-analyzer-iot-edge-python#14]
How to limit blob data storage usage when writing video.
Currently video has been writing. But I want to limit it under customer requirements.

**Comment by anilmur** [comment]
@omersalam  - instructions are at https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/manage-recording-policy

**Comment by omersalam** [comment]
Thankyou.

**Comment by naiteeks** [comment]
closing issue as I believe this is resolved.
