### ISSUE TITLE
How to get these data if Azure resource created in portal?

### ISSUE THREAD

**Issue by michaelcwang2** [Azure-Samples/video-analyzer-iot-edge-python#18]
On the [Quickstarts page](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/analyze-live-video-use-your-model-http?pivots=programming-language-python#get-the-sample-code), it says "Browse to the file share in the storage account created in the setup step above, and locate the env.txt file under the "deployment-output" file share. Click on the file, and then hit the "Download" button. The contents should open in a new browser tab, which should look like:" However if it's created manually in portal, how to find information like CONTAINER_REGISTRY_USERNAME_myacr="<your container registry username>"
     CONTAINER_REGISTRY_PASSWORD_myacr="<your container registry password>"<br>check "Token" under "Repository permissions" on right pane of "Container Registry" dashboard? Please commenr.
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jasonxian-msft** [comment]
Hi @michaelcwang2, when you created resources via the Portal, you should have [created a container registry](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/get-started-detect-motion-emit-events-portal#create-a-container-registry). To fill in the .env file with the ACR username and password, you can head to the Portal and click on the "Container Registry" resource. Then, click on the "Access keys" under the Settings blade and find the username and password.
