### ISSUE TITLE
Why don't see the exported CV module in the pipeline json at https://raw.githubusercontent.com/Azure/video-analyzer/main/pipelines/live/topologies/httpExtension/topology.json

### ISSUE THREAD

**Issue by michaelcwang2** [Azure-Samples/video-analyzer-iot-edge-python#23]
Please refer to [this session of Readme in edge folder](https://github.com/Azure-Samples/video-analyzer-iot-edge-python/blob/main/src/edge/readme.md#deploymentcustomvisiontemplatejson)<br>In this section of [generate and deploy...](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/analyze-live-video-custom-vision?pivots=programming-language-python#generate-and-deploy-the-deployment-manifest) of this [tutorial](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/analyze-live-video-custom-vision?pivots=programming-language-python#generate-and-deploy-the-deployment-manifest) there is a topology.json file quoted at https://raw.githubusercontent.com/Azure/video-analyzer/main/pipelines/live/topologies/httpExtension/topology.json <br> However, since the cv model which is used for inferencing is exported and deployed as module in edge device, why the section of this code `{
        "name": "inferencingUrl",
        "type": "String",
        "description": "inferencing Url",
        "default": "http://yolov3/score"
      },
      {
        "name": "inferencingUserName",
        "type": "String",
        "description": "inferencing endpoint user name.",
        "default": "dummyUserName"
      },
      {
        "name": "inferencingPassword",
        "type": "String",
        "description": "inferencing endpoint password.",
        "default": "dummyPassword"
      },` is url like **http://yolov3/score** and not like container registry. Please comment. 

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jasonxian-msft** [comment]
Hi @michaelcwang2 , yes you should be using `http://cv/score`.
