### ISSUE TITLE
Failed to run httpExtension example

### ISSUE THREAD

**Issue by wennycooper** [Azure-Samples/video-analyzer-iot-edge-python#34]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> docker run -d -p 5001:5001 --name httpextension httpextension:latest -p 5001

### Any log messages given by the failure
> docker logs httpextension 
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    app.run(host='0.0.0.0', port=httpServerPort)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 905, in run
    port = int(port)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

### Expected/desired behavior
> server should be running and listening on port 5001 

### OS and Version?
> Linux (ubuntu 18.04)

### Versions
> ubuntu 18.04

### Mention any other details that might be useful
It looks like the _arguments.p is a list, instead of an integer

> ---------------------------------------------------------------

**Comment by jasonxian-msft** [comment]
Hi @wennycooper, thanks for bringing this to our attention. 

Is this the sample you are trying to run?

https://github.com/Azure-Samples/video-analyzer-iot-edge-python/tree/main/src/edge/modules/httpExtension

**Comment by wennycooper** [comment]
Yes, that's the sample I'm trying to run.
And I think following code would fix this problem. FYR

parser.add_argument('-p', help='Port number to listen on.', type=int, default=8080)

**Comment by jasonxian-msft** [comment]
Thank you for the suggestion, we will reproduce the error and make the appropriate changes as soon as possible.
